In [1]:
import numpy as np
import gymnasium as gym

In [28]:
def value_iteration(env, gamma=0.99, theta=1e-6):
    n_states = env.observation_space.n
    n_actions = env.action_space.n

    V = np.zeros(n_states)  # State value function

    def one_step_lookahead(state, V):
        A = np.zeros(n_actions)
        for a in range(n_actions):
            for prob, next_state, reward, done in env.P[state][a]:
                A[a] += prob * (reward + gamma * V[next_state])
        return A

    iteration = 0
    while True:
        delta = 0
        for s in range(n_states):
            A = one_step_lookahead(s, V)
            best_action_value = np.max(A)
            delta = max(delta, abs(best_action_value - V[s]))
            V[s] = best_action_value
        iteration += 1
        if delta < theta:
            break

    # Extract policy
    policy = np.zeros(n_states, dtype=int)
    for s in range(n_states):
        A = one_step_lookahead(s, V)
        print(A)
        policy[s] = np.argmax(A)

    print(f"Value Iteration converged in {iteration} iterations.")
    return policy, V

In [19]:
def evaluate_policy(env, policy, episodes=10):
    total_rewards = []
    for _ in range(episodes):
        state = env.reset()[0]
        done = False
        total_reward = 0
        while not done:
            action = policy[state]
            state, reward, done, _, info= env.step(action)
            total_reward += reward
        total_rewards.append(total_reward)
    avg_reward = np.mean(total_rewards)
    print(f"Average reward over {episodes} episodes: {avg_reward}")
    return avg_reward

In [29]:
env = gym.make("CliffWalking-v0").unwrapped
optimal_policy, optimal_values = value_iteration(env)

print(optimal_policy)
# Optionally evaluate the learned policy
evaluate_policy(env, optimal_policy)

[-99.99990235 -99.99990235 -99.99990235 -99.99990235]
[-99.99990235 -99.99990235 -99.99990235 -99.99990235]
[-99.99990235 -99.99990235 -99.99990235 -99.99990235]
[-99.99990235 -99.99990235 -99.99990235 -99.99990235]
[-99.99990235 -99.99990235 -99.99990235 -99.99990235]
[-99.99990235 -99.99990235 -99.99990235 -99.99990235]
[-99.99990235 -99.99990235 -99.99990235 -99.99990235]
[-99.99990235 -99.99990235 -99.99990235 -99.99990235]
[-99.99990235 -99.99990235 -99.99990235 -99.99990235]
[-99.99990235 -99.99990235 -99.99990235 -99.99990235]
[-99.99990235 -99.99990235 -99.99990235 -99.99990235]
[-99.99990235 -99.99990235 -99.99990235 -99.99990235]
[-99.99990235 -99.99990235 -99.99990235 -99.99990235]
[-99.99990235 -99.99990235 -99.99990235 -99.99990235]
[-99.99990235 -99.99990235 -99.99990235 -99.99990235]
[-99.99990235 -99.99990235 -99.99990235 -99.99990235]
[-99.99990235 -99.99990235 -99.99990235 -99.99990235]
[-99.99990235 -99.99990235 -99.99990235 -99.99990235]
[-99.99990235 -99.99990235 -

KeyboardInterrupt: 